### ISSUE TITLE
Will using this get my account banned?

### ISSUE THREAD

**Issue by giridharvc7** [kahopoon/Pokemon-Go-Controller#14]
So i havent tried this out yet, but would using this method get me banned? I heard that this is against niantic's TOS

**Comment by T-Pham** [comment]
The pokemons now always escape after I catch them. Not sure if that means I have been banned.

**Comment by posixpascal** [comment]
I'm getting the same experience as @T-Pham. As soon as the Pokémon gets into the ball it breaks free and escapes. This happend to me 30 times in a row.

Neither am I able to receive any goods from pokestops nor can I enter an arena fight.
The PokeStops are detected (displayed with an image) but if I spin them nothing happens.
The Arena fights start just fine but as soon as any pokemon tries to attack it kicks me out.

Not sure if this is caused by any server lag but it seems kinda related to using Pokemon Go Controller. Can someone reproduce this or does this happen to anybody else except me and T-Pham?

**Comment by Hitscotty** [comment]
It's caused by the server lag, everyone experiences this from time to time.

**Comment by posixpascal** [comment]
Not sure tbh. I've experienced quite a few server lags from pokeballs freezing to maps not loading but in this case the map just loads fine pretty fast, I can login without problems and even access & remove pokemons from my bag. I was also able to purchase a few pokeballs from the shop without any noticeable lag.  Only thing not working is the catching/stops/arenas. Looks quite strange because it's always the same for every pokemon even for different levels. I'll try it again in a few hours and report in.

**Comment by T-Pham** [comment]
One thing worth mentioning is that Niantic is the company behind Pokemon Go as well as Ingress and they do have an anti-cheating system used for Ingress which resulted in many Ingress players getting banned. It's not hard for them to apply the same system for Pokemon Go.

**Comment by posixpascal** [comment]
According to this reddit thread https://www.reddit.com/r/pokemongo/comments/4ry7my/psa_spoofing_gps_locations_will_get_you_banned/ its a softban (same syndromes).

Also as the first comment states the ban should go away after 2 to 3 hours. I'll report in after I catch a pokemon.

**Comment by puttichan** [comment]
Well, of course you can get caught.
If you move too much with this, you will get perma banned because it is obvious that you are hacking.

Other than that, why the heck not?

**Comment by kahopoon** [comment]
absolutely you can't escape from banned if you move the map from united states to australia in a minute and both side you get something from it. this repo is not for making high rank of account but just showing romance of engineer :)
