### ISSUE TITLE
[ERROR] Failed binding IPv4 listening socket: Permission denied (13)

### ISSUE THREAD

**Issue by PaulLafytskyi** [kahopoon/Pokemon-Go-Controller#46]
App don't work

**Comment by saumilptl** [comment]
You seem to be using the emulator for the controller and any port below 1024 or so is not allowed on iOS emulators since they use local network.

Try the following:

change port 80 with 8080 
webServer.startWithPort(8080, bonjourName: "pokemonController");
and in readAndChangeXML.py
response = urllib2.urlopen("http://yourhostmachineiphere:8080/", timeout = 1)

**Comment by vincent144** [comment]
@saumilptl  +1

**Comment by irshadpc** [comment]
@saumilptl +1
