### ISSUE TITLE
User-friendly installation

### ISSUE THREAD

**Issue by ziyaddin** [kahopoon/Pokemon-Go-Controller#63]
It is very cool! Is it possible to make a user-friendly installation method for non-programmer users? I think, it can broaden the user audience.

**Comment by JensDebergh** [comment]
It's impossible to make a user friendly installation since you need xcode to get this project working in the first place. You can soften the experience by providing a guide, but there will always be hiccups by less experienced users.

You can try an improved project based on the ideas in this repository.

https://github.com/iam4x/pokemongo-webspoof

Makes it fairly "simple"

**Comment by MoOx** [comment]
Btw, to install something on an iOS device you need a Apple developer account (which is not free).

**Comment by JensDebergh** [comment]
@MoOx You can sign up for an account but not complete the process, at least that's what I have done.

**Comment by MoOx** [comment]
Yes but without a proper license, you won't be able to push the compiled stuff on your device, only in the simulator.

**Comment by JensDebergh** [comment]
I'm able to push my code on my device without a valid apple license. You need an apple developer account to actually be able to push towards the apple store. But for development you don't need a completely set up account.

**Comment by MoOx** [comment]
Weird. Maybe that's new. A few months ago (or last year) I had to buy a license... :'(

**Comment by deden** [comment]
Deploy on your device with free provisioning will be valid until 7 days (with Xcode 7)

**Comment by clay-to-n** [comment]
@MoOx Yup, they removed that requirement about a year ago.
